# Generated by Django 3.2.11 on 2022-02-24 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdate',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userdate',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
