# Generated by Django 3.2.11 on 2022-02-24 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220224_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdate',
            name='published_date',
        ),
        migrations.AddField(
            model_name='userdate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
