# Generated by Django 3.2.11 on 2022-02-25 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220224_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdate',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='height',
            field=models.FloatField(verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='userdate',
            name='weight',
            field=models.FloatField(verbose_name='体重'),
        ),
    ]
