# Generated by Django 3.2.11 on 2022-02-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220225_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdate',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=''),
        ),
    ]
